# Generated by Django 3.1.4 on 2022-01-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
    ]
