# Generated by Django 3.1.4 on 2022-02-27 17:59

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20220227_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[leads.models.my_year_validator]),
        ),
    ]
